### ISSUE TITLE
Home Page Development (excluding brand video)

### ISSUE THREAD

**Issue by garima-236** [Samagra-Development/Samagra-Website#10]
- [x] Sitemap & Navigation bar reorganisation 
- [x] Re-development of homepage components (brand video will come in later instead of banner GIF)
- [x] Samagra logo in transparent layer looks in low quality it can be improved. 1. Logo in a transparent layer. (https://prnt.sc/In3_J5yh25HO)

Link to wireframe (<<link to be added>>)

**Comment by garima-236** [comment]
Homepage wireframe vF to be shared by OT ~ by 1st/2nd week of April

**Comment by garima-236** [comment]
https://www.figma.com/file/KZudtpBn8lFl0O0CJonbeA/Samagra?type=design&node-id=1%3A79463&mode=dev

Hi @karntrehan @prtkjakhar @riya-2206 
Here is the final figma file with the wireframe (incl content), specs and prototype + animations for the homepage. 

Do let us know if anything else is needed from our end.

**Comment by riya-2206** [comment]
Hi Garima, have raised the PR, you can refer the below link to check the preview-
https://deploy-preview-33--samagra.netlify.app/

have added footer and also integrated page with cms content
don't test cms using preview link because it will directly affect the main website and it is not merged yet

Let me know in case of any changes required

**Comment by riya-2206** [comment]
Hey Garima,
Have made all the changes which we discussed over call. Let me know if any changes required
Preview Link:  https://deploy-preview-33--samagra.netlify.app/

**Comment by aayush-malik** [comment]
@karntrehan @riya-2206 @prtkjakhar edits on homepage to be made: 

- Our Work: Please enable configurability of 'Learn More' buttons text in cards 
- Headers of all sections to be made configurable
- Our Model: Please make the icons configurable
- LinkedIn button: Please enable option to show/hide the text + button
- Carousel: Please enable configurability of the carousel on CMS
- Footer + Nav Bar: Please enable configurability of both sections on CMS
- CMS: Please remove 'Media' (below the sticky banner option) from the CMS page

**Comment by aayush-malik** [comment]
@karntrehan  @riya-2206  @prtkjakhar P2 edits on homepage to be made:

- [ ] Carousel: Please enable configurability of the carousel on CMS
- [ ] Footer + Nav Bar: Please enable configurability of both sections on CMS
- [ ] CMS: Please remove 'Media' (below the sticky banner option) from the CMS page

**Comment by karntrehan** [comment]
P1 (#38) and P2 (#39) extracted to separate tickets. Closing this now.
