### ISSUE TITLE
[BUG]: Blog page

### ISSUE THREAD

**Issue by garima-236** [Samagra-Development/Samagra-Website#12]
# Bug report

**What is the current behavior?**

- [x] On the Blog page, there is unnecessary white space at the bottom of the page above the footer. 1. Home page > Scroll down 2. Click on Blog (https://prnt.sc/WMv9k0eYBGTr)
- [ ] There is a Bug in the CMS perhaps basically when copy-pasting from a word document in the main body the formatting is not retained especially issues in formatting bullets and cursor randomly position itself to the top / bottom whilst typing / making edits 

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**

Node.js version: 
NPM/Yarn version
Operating System: 
Additional tools:

**Comment by riya-2206** [comment]
have removed extra padding from the blog page

**Comment by garima-236** [comment]
Is there a preview link for this?


*Garima Sood*

Senior Associate, Outreach | +91 9910068723

Samagra | Transforming Governance

Address: 9/5 Sarvapriya Vihar, New Delhi-16
***@***.***,77.1994501,17z/data=!3m1!4b1!4m5!3m4!1s0x390ce273981e5dfb:0x7bfceb198af17562!8m2!3d28.5566128!4d77.2016388?shorturl=1>

Website: www.samagragovernance.in

Follow Us: LinkedIn
<https://www.linkedin.com/company/samagra-transforming-governance/> |
YouTube <https://www.youtube.com/channel/UCfkXErS-f87xUQkmSKSC8bg> |
Instagram <https://www.instagram.com/samagragovernance/?hl=en>

**Comment by riya-2206** [comment]
https://deploy-preview-20--samagra.netlify.app/blog

**Comment by garima-236** [comment]
Yes, it looks good - you can also push this :)

Regards,

*Garima Sood*

Senior Associate, Outreach | +91 9910068723

Samagra | Transforming Governance

Address: 9/5 Sarvapriya Vihar, New Delhi-16
***@***.***,77.1994501,17z/data=!3m1!4b1!4m5!3m4!1s0x390ce273981e5dfb:0x7bfceb198af17562!8m2!3d28.5566128!4d77.2016388?shorturl=1>

Website: www.samagragovernance.in

Follow Us: LinkedIn
<https://www.linkedin.com/company/samagra-transforming-governance/> |
YouTube <https://www.youtube.com/channel/UCfkXErS-f87xUQkmSKSC8bg> |
Instagram <https://www.instagram.com/samagragovernance/?hl=en>

**Comment by garima-236** [comment]
Ctrl / Command + Shift + V for pasting accuracy on the blog page.
