### ISSUE TITLE
[ENHANCEMENT]: Careers Page

### ISSUE THREAD

**Issue by garima-236** [Samagra-Development/Samagra-Website#13]
## Feature request

**What is the expected behavior?**

- [x] Banner on the Careers page, slides are not changing automatically, can be added rotation. 1. Home page > Careers Page (https://prnt.sc/dDsO0iQmAFsw)

**What is motivation or use case for adding/changing the behavior?**

**How should this be implemented in your opinion?**

**Are you willing to work on this yourself?**
yes

**Comment by riya-2206** [comment]
Have added auto slide feature in carousal of career page

**Comment by garima-236** [comment]
Is there a preview link for this?

*Garima Sood*

Senior Associate, Outreach | +91 9910068723

Samagra | Transforming Governance

Address: 9/5 Sarvapriya Vihar, New Delhi-16
***@***.***,77.1994501,17z/data=!3m1!4b1!4m5!3m4!1s0x390ce273981e5dfb:0x7bfceb198af17562!8m2!3d28.5566128!4d77.2016388?shorturl=1>

Website: www.samagragovernance.in

Follow Us: LinkedIn
<https://www.linkedin.com/company/samagra-transforming-governance/> |
YouTube <https://www.youtube.com/channel/UCfkXErS-f87xUQkmSKSC8bg> |
Instagram <https://www.instagram.com/samagragovernance/?hl=en>

**Comment by riya-2206** [comment]
https://deploy-preview-19--samagra.netlify.app/careers

**Comment by garima-236** [comment]
Thanks! Looks good :)
You can push this change Riya.

*Garima Sood*

Senior Associate, Outreach | +91 9910068723

Samagra | Transforming Governance

Address: 9/5 Sarvapriya Vihar, New Delhi-16
***@***.***,77.1994501,17z/data=!3m1!4b1!4m5!3m4!1s0x390ce273981e5dfb:0x7bfceb198af17562!8m2!3d28.5566128!4d77.2016388?shorturl=1>

Website: www.samagragovernance.in

Follow Us: LinkedIn
<https://www.linkedin.com/company/samagra-transforming-governance/> |
YouTube <https://www.youtube.com/channel/UCfkXErS-f87xUQkmSKSC8bg> |
Instagram <https://www.instagram.com/samagragovernance/?hl=en>
