### ISSUE TITLE
[BUG]: Read more section of program page

### ISSUE THREAD

**Issue by garima-236** [Samagra-Development/Samagra-Website#22]
I was trying to update the links in the read more section of this page but there seems to be a bug here. It is not giving me a full list of options from the media page to choose from. It maybe the case that this might be happening for other program pages too on the website. 

https://samagragovernance.in/project/nipun-bharat-cell/

**Comment by garima-236** [comment]
@riya-2206  I went at the backend to test out the read more section but facing a similar challenge, the complete list of blogs & media pages isn't reflecting for some reason

**Comment by komalmishraa** [comment]
I was looking forward to work on this one, but when i visited read more section and media pages its displaying whole list of blogs now

**Comment by riya-2206** [comment]
Hey Komal,  can you please attach screenshot so it will be more clear because I can see media list in the read more section

**Comment by komalmishraa** [comment]
yeah that's what i'm saying that the bug has been fixed ig coz media list is visible in read more section
