### ISSUE TITLE
Content Assets Landing Page Template

### ISSUE THREAD

**Issue by garima-236** [Samagra-Development/Samagra-Website#25]
- [ ] Create a new template for content assets landing page.

**Comment by garima-236** [comment]
Wireframe vF to be shared ~1st April

**Comment by aayush-malik** [comment]
Hi @karntrehan @riya-2206 @prtkjakhar please find below the final wireframes of the content assets landing page:

1. Desktop View (Prototype): https://www.figma.com/proto/KZudtpBn8lFl0O0CJonbeA/Samagra?page-id=970%3A5553&type=design&node-id=970-6586&viewport=93%2C30%2C1.91&t=1PpXPMYHq0uFzA0B-1&scaling=min-zoom&mode=design
2. Mobile View (Prototype): https://www.figma.com/proto/KZudtpBn8lFl0O0CJonbeA/Samagra?page-id=970%3A5553&type=design&node-id=970-7024&viewport=93%2C30%2C1.91&t=PMkMj1fzEvZ6Mf8d-1&scaling=min-zoom&mode=design
3. Wireframe: https://www.figma.com/file/KZudtpBn8lFl0O0CJonbeA/Samagra?type=design&node-id=970%3A5553&mode=design&t=dwckWcSGNB3GsjDm-1

@karntrehan from our discussion yesterday, please hard code the 4 boxes that appear in the desktop view.

**Comment by riya-2206** [comment]
Hi @aayush-malik @garima-236 ,

Can you please provide banner image for landing page. I can't access it from figma.

**Comment by aayush-malik** [comment]
Hi @riya-2206, the image in the wireframe is a stock image. For now, you can use this: https://drive.google.com/file/d/150Jg6aYAv0uUVgA2YybJUpNBBOxYX-7Z/view?usp=sharing

Please do enable ability for us to edit the image on the CMS.

**Comment by prtkjakhar** [comment]
Bugs:
- Our Assets not opening in mobile view from menu

Enhancements:
- Configurability show/hide of Read More in Assets card

**Comment by riya-2206** [comment]
Hey @aayush-malik,
Need one clarification for this - Our Assets not opening in mobile view from menu
here in mobile when we click on our asset it opens dropdown(existing logic), 
we can keep only one functionality for mobile view either it opens dropdown or it opens asset page 
![image](https://github.com/Samagra-Development/Samagra-Website/assets/161353600/bb5f9553-86ff-44f7-8d2a-a5e223fb567f)

**Comment by riya-2206** [comment]
Hey @aayush-malik,
Need one clarification for this - Our Assets not opening in mobile view from menu
here in mobile when we click on our asset it opens dropdown(existing logic), 
we can keep only one functionality for mobile view either it opens dropdown or it opens asset page 
![image](https://github.com/Samagra-Development/Samagra-Website/assets/161353600/bb5f9553-86ff-44f7-8d2a-a5e223fb567f)

**Comment by riya-2206** [comment]
will update these changes and will share the PR link

**Comment by aayush-malik** [comment]
@riya-2206- as mentioned by @prtkjakhar, the sub menu item under 'Our Assets' to land on this page can be called '**Overview**'. This will be the first option in the sub-menu.

**Comment by riya-2206** [comment]
Hi @aayush-malik ,

Have made all the above mentioned changes.
PFA preview link and let me know if we can merge this PR-
https://deploy-preview-41--samagra.netlify.app/assets/

**Comment by aayush-malik** [comment]
Hi @riya-2206, looks good! Can merge with PR, I'm guessing that will also enable CMS edit access for us? We do not want to make the page live immediately, so just double-checking on that.

**Comment by riya-2206** [comment]
Hey @aayush-malik, after merging PR cms edit will be available for you but page will also become live

**Comment by aayush-malik** [comment]
@riya-2206 in that case, let's wait on this. We do not want to make the page live immediately.

**Comment by aayush-malik** [comment]
@riya-2206 just thinking on the lines of how we did it for the homepage: can we make it live on an alternative link, which no one can access without the link? The difference I see here from the homepage in this case is that the 'Our Assets' button will get hyperlinked, and people will be able to access it. Can we make the hyperlink on 'Our Assets' a show/hide functionality? This will enable us to edit elements of the webpage without it being visible to everyone, and we can switch it to 'show' once we think we'd like to make it live. Please let me know if this is feasible, thanks!

**Comment by riya-2206** [comment]
what I can do is I will remove the click events from navbar for both mobile and desktop and you can visit the page by using /assets. And whenever page is ready I will add clickable buttons active for Our Assets button(desktop) and Overview Button(mobile) Shall I do?
@aayush-malik

**Comment by aayush-malik** [comment]
@riya-2206 sounds good, please go ahead.

**Comment by riya-2206** [comment]
@aayush-malik have merged the PR you can check the page using below mentioned link:
https://samagragovernance.in/assets/
