### ISSUE TITLE
[BUG] Amrit Series Page

### ISSUE THREAD

**Issue by karntrehan** [Samagra-Development/Samagra-Website#3]
- [x] Can be added hyperlink to the email address. Home page > Amrit series.  
- [ ] The video is taking a longer time to render on the page till it shows white blank space. Home Page > Click on Amrit series. Scroll down and click on learn more for (""KRUSHI SAMIKSHA KENDRA"")

**Comment by riya-2206** [comment]
Have added hyperlink for Amritseries page, needed one confirmation do I need to add hyperlink for individual case studies also, if yes then I will have to break footer2 field of cms in two parts one for reference text and another one for email
e.g. 1. Write to us at:  2. outreach@samagragovernance.in

**Comment by riya-2206** [comment]
![Screenshot 2024-03-01 174741](https://github.com/Samagra-Development/Samagra-Website/assets/161353600/e9d5637c-fb6c-422d-a3f7-8992d9a958b1)
