### ISSUE TITLE
Governance Decluttered Webpage

### ISSUE THREAD

**Issue by aayush-malik** [Samagra-Development/Samagra-Website#46]
Hi @karntrehan @prtkjakhar @riya-2206, creating this ticket for the creation of the governance decluttered webpage.  The wireframe is linked below:
Desktop: https://www.figma.com/design/A1hSB1v5szqlRrq7O3Ca7Q/Samagra-website?node-id=95-3003&t=jjbGLHmhB7lHLITX-4
Mobile: https://www.figma.com/design/A1hSB1v5szqlRrq7O3Ca7Q/Samagra-website?node-id=44-2264&t=jjbGLHmhB7lHLITX-4

**Comment by karntrehan** [comment]
Questions: 
 - [ ] Where is the following going to come from? 
![Image](https://github.com/Samagra-Development/Samagra-Website/assets/5885669/9600b409-01e2-4d7c-a853-61876ae714a8)

- [ ] Are these counts to be updated? 
![Image](https://github.com/Samagra-Development/Samagra-Website/assets/5885669/b6b1352e-2abc-4654-8232-94d1fec71b8f)

- [ ] Is this to update on Instagram? If so, we would need to link to instagram. Is that high ROI?
![Image](https://github.com/Samagra-Development/Samagra-Website/assets/5885669/36ae0ed3-07e8-40c3-8d26-3dee224d559c)

**Comment by aayush-malik** [comment]
Hey @karntrehan, responding to the questions:
1. We will provide the bifurcations of the reel in these categories.
2. Yes, the counts are to be updated
3. We would ideally like to link instagram here, as we do envision the website to become a high-frequency touchpoint for our TG.

On 2 & 3, would like to understand the effort and challenges on linking instagram with the website with count updations and actions on website getting updated on instagram. If it is a significant effort, we can reconsider. Please let us know, thanks!

**Comment by aayush-malik** [comment]
Hey @karntrehan, for pt 1 above, providing the categorization in this sheet: https://docs.google.com/spreadsheets/d/1fr8FXk9R5UiuO8qxF_SB2G-KUppCkqD5_JMtcfmfA7U/edit?usp=sharing

**Comment by karntrehan** [comment]
## Option 1: Manual Embed 
1. OT create a post
2. OT adds Thumbnail
3. OT adds category 
4. OT add embed link as well: https://developers.facebook.com/docs/instagram/embed-button 

### Pros: 
1. OT can decide which reel to post on website.
2. OT can also post non reel content
3. Updated likes on website itself.
4. Medium dev effort
5. Support to play reel on website itself. 

### Cons: 
1. Manual effort from OT

## Option 2: Auto Oembed
1. Eng builds the OEmbed app and gets it approved from Meta
2. OT creates post
3. Oembed auto pulls post

### Pros: 
1. Auto population of reels - No manual effort.

### Cons:
1. Posts will not contain categories
2. OT cannot decide which reel to post on website.
3. Highest dev effort
4. No play of reel on website.

## Option 3: Redirect to Instagram
1. OT create a post
2. OT adds Thumbnail
3. OT adds category 
4. OT adds caption
5. OT adds post link

### Pros: 
1. OT can decide which reel to post on website.
2. OT can also post non reel content
3. Smallest dev effort

### Cons:
1. No updated likes / views on website.
2. No play of reel on website.

**Comment by karntrehan** [comment]
Load more to be clarified from OT. Option 2 is a go-ahead.

**Comment by aayush-malik** [comment]
To show more than the first 9 videos in the grid, we can have a functionality similar to the button below, to ensure the same amount of vertical space is taken by the grid of videos at each point in time. 

![Image](https://github.com/Samagra-Development/Samagra-Website/assets/163277765/d151ea90-fd3b-4d45-9ecb-517483fc2e35)

**Comment by riya-2206** [comment]
Hey @aayush-malik , 
thanks for the update. Can you also provide the link of the instagram profile which needed to be linked.

cc @karntrehan

**Comment by aayush-malik** [comment]
Hey @riya-2206, link to IG: https://www.instagram.com/samagragovernance/

**Comment by karntrehan** [comment]
Feedback: 

- [ ] Move from video file to youtube link
- [ ] Make full item clickable 
- [ ] Make 4 columns on web view
- [ ] Add menu item under assets when page ready
- [ ] Move categories to free text from a dropdown

**Comment by riya-2206** [comment]
@aayush-malik , will make our assets and decluttered page live, also shall I add decluttered page in the navbar and footer?

**Comment by aayush-malik** [comment]
@riya-2206, please do add it in the nav bar & footer under 'Our Assets'. Thank you.

**Comment by riya-2206** [comment]
Hey @aayush-malik,  done.
