### ISSUE TITLE
Team Page

### ISSUE THREAD

**Issue by tanusha-samagra** [Samagra-Development/Samagra-Website#67]

**Comment by tanusha-samagra** [comment]
Hi Team
Hope you are well.

Here is the wireframe for team page: https://www.figma.com/design/A1hSB1v5szqlRrq7O3Ca7Q/Samagra-website?node-id=688-1174&node-type=canvas&t=mwo7wkLO2gdWMTQe-0

Shall be discussing more in the Sync today!

Thanks:)

**Comment by karntrehan** [comment]
Will be deployed today.
