### ISSUE TITLE
Create template for old case study - Antyodaya Saral

### ISSUE THREAD

**Issue by garima-236** [Samagra-Development/Samagra-Website#9]
## Feature request

**What is the expected behavior?**
Similar to how new case study template (i.e. GO-SUGAM) was designed at the backend, a similar template needs to be created for old case studies (i.e. Antyodaya Saral)

**What is motivation or use case for adding/changing the behavior?**
The template for old case study is different from new case study

**How should this be implemented in your opinion?**
Link to Wireframe (<<will add link here>>)

**Are you willing to work on this yourself?**
yes

**Comment by karntrehan** [comment]
Wireframe to be received on Wednesday.

**Comment by garima-236** [comment]
Link to the wireframe [https://drive.google.com/file/d/1-C5-EwYJHwtxozRj1B1LEhNS7FGsByi_/view?usp=sharing](url)

For the same, please include the features that were a part of the Go-Sugam webpage as well. 

Additionally, please accommodate for these changes in the wireframe: 

1. The grey section with Antyodaya Saral in the start will be replaced with a gif like Go-Sugam. 
2. For the infographics of citizen and the officer, we would need the option of including upto 5 points as per need. 
3. Please remove the maroon coloured arrows in the section named 'Here is how the Haryana government worked in a mission mode...'. 
4. For the same section, we would need a toggle option allowing us to plug in the video (the one with the Youtube button) or plug in the 3 enablers (named Antyodaya Saral online platform, Citizen touchpoints and enablers) or both, basically an option to switch between video or cards or both. 
5. For the 'Insights from ground' section, can do a single image plugged instead of a photo bundle. 
6. Lastly, the order of the last two sections can be kept same as the previous case studies i.e. the 'Partner with us' section comes first and then the previous case studies cards come in.

**Comment by karntrehan** [comment]
To be done on Monday. OT to have demo on Tuesday.

**Comment by riya-2206** [comment]
have pushed the changes and raised the pr

**Comment by garima-236** [comment]
- [ ] Bug on landing page (card not showing) was closed
